### ISSUE TITLE
Add query to meta_knowledge_graph to retrieve "possible" nodes/edges

### ISSUE THREAD

**Issue by sierra-moxon** [TranslatorSRI/SRI_testing#2]
Perhaps instead of relying on KPs to provide what they can return, query the MKG endpoint to see what they can return.

- possibly add 'biolink-model version' to the MKG endpoint schema.
- possibly use biolink-model to validate associations

example MKG endpoint:
https://icees.renci.org:16342/meta_knowledge_graph

**Comment by putmantime** [comment]
We are now proposing a field in the smartapi spec that would point to test triples in the kps repo.
The metakg supplies the data model but no examples.
One future possibility would be to put examples in the metakg with the schema.

This did however inspire two additional testing scenarios:
  We will test to first see if there is a metakg for each KP (which there currently is not in all cases).
  We can also use the metakg to ensure that sample data has been provided for all triple types.

**Comment by RichardBruskiewich** [comment]
Tim's comments are a duplication of Issue #14. PR #27 resolves the `test_data_location` mechanism for getting sample data.
