### ISSUE TITLE
Missing ARA query parameter example

### ISSUE THREAD

**Issue by RichardBruskiewich** [TranslatorSRI/SRI_testing#8]
The [**one hop** ARA instructions](https://github.com/TranslatorSRI/SRI_testing/tree/main/onehop#ara-instructions) say:

```
3. If an ARA needs particular query options, these can also be added to the json (See Ranking_Agent/ARAGORN.json)
```

But there don't appear to be any such query options within the [Ranking_Agent/ARAGORN.json](https://github.com/TranslatorSRI/SRI_testing/blob/main/onehop/templates/ARA/Ranking_Agent/ARAGORN.json) file?

**Comment by cbizon** [comment]
Hmm, we removed the need for that query option, and also removed it from the json I guess.    Probably the best thing to do is update the instructions to remove that statement/reference.  AFAIK, there aren't any ARAs that want/need query options.
